apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/security
patches:
  - path: patch-optional.yaml
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/server/ingress/hosts/0/host
        value: vault.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/ingress/hosts/0/host
        value: gpm.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: gatekeeper-policy-manager
      namespace: argocd
