apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/semantification
patches:
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/ingressHostName
        value: semantification.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: semantification-service
      namespace: argocd
