apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - data-storage-service.yaml
  - dss-db.yaml
  - metadata-service.yaml
  - prediction-service.yaml
  - ui-gateway.yaml
  - kg-exporter.yaml