apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx-ingress
    repoURL: ghcr.io/nginxinc/charts
    targetRevision: 1.1.3
    helm:
      valuesObject:      
        controller:
          kind: deployment
          config:
            entries:
              external-status-address: "10.1.14.160"
          nodeSelector:
            master: "true"
          service:
            ## The type of service to create for the Ingress Controller.
            type: NodePort
            httpPort:
              ## Enables the HTTP port for the Ingress Controller service.
              enable: true

              ## The HTTP port of the Ingress Controller service.
              port: 80

              ## The custom NodePort for the HTTP port. Requires controller.service.type set to NodePort.
              nodePort: 31080

              ## The HTTP port on the POD where the Ingress Controller service is running.
              targetPort: 80

            httpsPort:
              ## Enables the HTTPS port for the Ingress Controller service.
              enable: true

              ## The HTTPS port of the Ingress Controller service.
              port: 443

              ## The custom NodePort for the HTTPS port. Requires controller.service.type set to NodePort.
              nodePort: 31443

              ## The HTTPS port on the POD where the Ingress Controller service is running.
              targetPort: 443

          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Equal"
              effect: "NoSchedule"        
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

