apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/dell-uc2
patches:
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/ingressHostName
        value: uc2-workload.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: uc2-workload-service
      namespace: argocd
